name: 采集全部数据

on:
  workflow_dispatch:  # 手动触发工作流按钮

jobs:
  run-trendhunter:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 创建必要的目录
      - name: Ensure directories
        run: mkdir -p TrendHunter

      # 运行 Python 脚本开始采集全部数据
      - name: Run Python script
        run: python Get5p-ALL.py

      # 提交生成的报告文件和模型文件到仓库
      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加当前仓库目录下的所有文件
          git add lottery_data.csv
  
          git commit -m "Auto-generate TrendHunter MD report and update model" || echo "No changes to commit"
          git push || echo "Push failed. Check GitHub token or repository permissions."
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
